#coding=utf-8
"""
Django settings for apitools project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys

reload(sys)
sys.setdefaultencoding('utf-8')

PRODUCTION = False
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, os.path.join(BASE_DIR, 'third_party'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '******************************'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['apitools.youku-game.com',
                 '127.0.0.1',
                 ]

GUEST = [':guest', ':wangxingtong']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'delayed_shipping',
    'index',
    'check_order',
    'check_rich'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apitools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'apitools.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

if PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql', # DB driver
            'NAME': '******************************', # DB name
            'USER': '******************************', # DB user
            'PASSWORD': '******************************', # DB password
            'HOST': '******************************', # DB host
            'PORT': 3306, # DB port
        },
                  
        'apiserver_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': '******************************',
            'USER': '******************************',
            'PASSWORD': '******************************',
            'HOST': '******************************',
            'PORT': 3306,
        },
     
        'u8server_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': '******************************',
            'USER': '******************************',
            'PASSWORD': '******************************',
            'HOST': '******************************',
            'PORT': 3306,
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql', # DB driver
            'NAME': '******************************', # DB name
            'USER': '******************************', # DB user
            'PASSWORD': '******************************', # DB password
            'HOST': '******************************', # DB host
            'PORT': 3306, # DB port
        },
                  
        'apiserver_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': '******************************',
            'USER': '******************************',
            'PASSWORD': '******************************',
            'HOST': '******************************',
            'PORT': 3306,
        },
     
        'u8server_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': '******************************',
            'USER': '******************************',
            'PASSWORD': '******************************',
            'HOST': '******************************',
            'PORT': 3306,
        },
         
    }


DATABASE_ROUTERS = ['delayed_shipping.routers.DelayedShippingRouter']

"""cache settings"""
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Aisa/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    # os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR,'node_modules'),
)

STATIC_ROOT = (os.path.join(BASE_DIR, 'static'))
